name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
      continue-on-error: false

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test1
      run: chmod +x ../../bashScript.sh  ../../bashScript.sh


